[env:esp32-devkit]
platform  = espressif32
board     = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed  = 921600

build_src_filter = +<*.cpp> +<*.h>
build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DGPS_UART_NUM=2
    -DGPS_RX_PIN=16
    -DGPS_TX_PIN=17
    -DGPS_BAUD=9600
    -DLED_PIN=2
    -DDEFAULT_I2C_SDA_PIN=21
    -DDEFAULT_I2C_SCL_PIN=22
    -I../shared

lib_deps =
    mikalhart/TinyGPSPlus @ ^1.0.3
    olikraus/U8g2 @ ^2.36.18
    dfrobot/DFRobot_QMC5883 @ ^1.0.0
    adafruit/Adafruit HTU21DF Library @ ^1.1.2

[env:esp32-c3-supermini]
platform  = espressif32
board     = esp32-c3-devkitm-1
framework = arduino

monitor_speed = 115200
upload_speed  = 921600

build_src_filter = +<*.cpp> +<*.h>
build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DGPS_UART_NUM=1
    -DGPS_RX_PIN=20
    -DGPS_TX_PIN=21
    -DGPS_BAUD=9600
    -DLED_PIN=8
    -DLED_ACTIVE_LOW=0
    -I../shared

lib_deps =
    mikalhart/TinyGPSPlus @ ^1.0.3
    olikraus/U8g2 @ ^2.36.18
    dfrobot/DFRobot_QMC5883 @ ^1.0.0
    adafruit/Adafruit HTU21DF Library @ ^1.1.2
